---
kind: pipeline
type: ssh
name: create-docker-images

server:
  host:
    from_secret: server_host_umac
  user:
    from_secret: server_host_umac_user
  ssh_key:
    from_secret: ssh_key_umac

steps:
- name: git_login
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - echo $PASSWORD | docker login -u $USERNAME --password-stdin
  - docker buildx create --name multiarch1 --driver docker-container --use
  when:
    event:
    - promote

- name: build_test_alpine_as_latest
  commands:
  - docker build --tag andrey0001/strongswan:latest .
  - docker rmi andrey0001/strongswan:latest
  when:
    branch:
    - alpine  

- name: build_and_push_alpine_as_latest
  commands:
    - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag andrey0001/strongswan:latest --tag andrey0001/strongswan:${DRONE_BRANCH} .
  when:
    branch:
    - alpine
    event:
    - promote

node:
  instance: umac
  type: ssh

